use_frameworks!

target 'GoogleDriveFilePicker_Tests' do
  pod 'GoogleDriveFilePicker', :git => 'https://github.com/fed933/GoogleDriveFilePicker.git', :branch => "master"
  pod 'PureLayout', '~> 3.0.2'
  
end
